
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqiuljtbildhwgsgnfbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xaXVsanRiaWxkaHdnc2duZmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDA4ODMsImV4cCI6MjA2MDE3Njg4M30.cTyNPALPFlimzEf2bj3pb1F3yeYecTqYwIs7jCTU9Uc";

// Create a custom type that extends Database
export type CustomDatabase = Database;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
